# Generated by Django 3.2.5 on 2022-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=64, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_customer',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='user',
            name='flat',
            field=models.CharField(max_length=64, null=True, verbose_name='№ квартиры'),
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(max_length=64, null=True, verbose_name='№ дома'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_customer',
            field=models.CharField(max_length=64, null=True, verbose_name='Фамилия получателя'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер для связи'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=64, null=True, verbose_name='Улица'),
        ),
    ]
