# Generated by Django 3.2.5 on 2022-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220830_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_customer',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Фамилия получателя'),
        ),
    ]
