# Generated by Django 3.2.5 on 2022-08-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220827_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.display', verbose_name='Диагональ(дюйм.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.memory', verbose_name='Память (гб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=19, verbose_name='Цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='В наличии(ед.)'),
        ),
    ]
