# Generated by Django 3.2.5 on 2022-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Москва', max_length=64, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliverytype',
            field=models.CharField(default='Самовывоз', max_length=64, verbose_name='Cпособ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name_customer',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='flat',
            field=models.CharField(max_length=64, null=True, verbose_name='№ квартиры'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=64, null=True, verbose_name='№ дома'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_customer',
            field=models.CharField(max_length=64, null=True, verbose_name='Фамилия получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(max_length=64, null=True, verbose_name='Cпособ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер для связи'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=64, null=True, verbose_name='Улица'),
        ),
    ]
