# Generated by Django 3.2.5 on 2022-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220822_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=64, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverytype',
            field=models.CharField(max_length=64, null=True, verbose_name='Cпособ доставки'),
        ),
    ]
