# Generated by Django 3.2.5 on 2022-08-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220822_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateofdelivery',
            field=models.DateField(null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=2, max_length=64, verbose_name='Общая цена'),
            preserve_default=False,
        ),
    ]
