# Generated by Django 3.2.5 on 2022-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(max_length=64, null=True, verbose_name='Общая цена'),
        ),
    ]
