# Generated by Django 3.2.5 on 2022-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateofdelivery',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverytype',
            field=models.CharField(max_length=64, verbose_name='Cпособ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name_customer',
            field=models.CharField(max_length=64, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flat',
            field=models.CharField(max_length=64, verbose_name='№ квартиры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=64, verbose_name='№ дома'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name_customer',
            field=models.CharField(max_length=64, verbose_name='Фамилия получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(max_length=64, verbose_name='Cпособ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='Номер для связи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='Общая цена'),
        ),
    ]
