# Generated by Django 3.2.5 on 2022-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20220830_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=64, null=True, verbose_name='Адрес доставки'),
        ),
    ]
