# Generated by Django 3.2.5 on 2022-09-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер телефона'),
        ),
    ]
