# Generated by Django 3.2.5 on 2022-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name_customer',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_customer',
            field=models.CharField(max_length=64, null=True, verbose_name='Фамилия покупателя'),
        ),
    ]
